### ISSUE TITLE
Firefox-mobile does not work on latest

### ISSUE THREAD

**Issue by bfra2373** [mouffa/pinephone#1]
Issue might just be on my side but using 
Arch
pinephone 1.2 
6.0.10-1-danctnix
gnome 43.2

Can't click with the onscreen window. I can navigate with keyboard.

**Comment by mouffa** [comment]
@bfra2373 I am using the latest Phosh on the stable branch and it works, try to reinstall both Firefox and the mobile configuration package, better remove the packages with the `-Rs` switch and re-install with `-S`

`sudo pacman -Rs firefox mobile-config-firefox`

`sudo pacman -S firefox mobile-config-firefox`

**Comment by bfra2373** [comment]
I tried but i did not worked. it might not be an issue with firefox... i do have an error message when launching firefox 
`[GFX1-]: glxtest: DRM render node not clearly detectable. Falling back to using the only one that was found` &` va-api test failed:failed to initialise VAAPI connection`.. but i'm not sure it is relevant.. but surely it is not linked to your the mobile config. do you have any clues as where I could find an answer to that? It was working just fine in the previous version maybe I could try to downgrade see if the issue persist?

**Comment by bfra2373** [comment]
downgrading firefox to 107.1 did solve the issue. should I report this?

**Comment by mouffa** [comment]
@bfra2373 the `va-api` is the interface for the video acceleration through the GPU, it seems like a Firefox's problem with the GPU communication this is why it complains about the DRM. Indeed the videos play correctly only with Firefox on Pinephone, any other player like `mpv` lags with high resolution so probably Firefox is able to use the GPU features, I have tried a little to activate the `va-api` for `mpv` but it didn't work.

I had a similar problem with Firefox 108.0-1 on Manjaro Gnome Desktop where it would mess up the theme and I had to turn off the system theme for Firefox through the Layouts configuration tool.

If the problem is with Firefox the right place to open an issue would be the repository for Firefox on Pinephone which is an `aarch64` device.

I have always had problem with locating the maintainer of a package, the general concept is that the image is built based on a profile using the `buildarmimg` command which reads the profile and starts collecting the packages and builds the image

https://github.com/manjaro-pinephone/phosh/

if you follow the links from there `image profiles > editions > phosh` you reach in the following file which says that probably Philm and Spikerquy maintain the packages though it says is for `arm-unstable` and `arm-testing` branches only, you can check your branch with 

`pacman-mirrors -G`

https://github.com/manjaro-pinephone/arm-profiles/blob/master/editions/phosh

**Comment by bfra2373** [comment]
@mouffa thank's a lot for all the info! I'll try to get in touch with the maintainer :)

**Comment by mouffa** [comment]
@bfra2373 I am using Firefox `107.0.1-1` and I am on the `arm-stable` so you are probably on the `arm-unstable` branch because even the `arm-testing` does not cause problems most of the times, you can switch to `arm-stable` and downgrade the packages with the following commands

`sudo pacman-mirrors --api --set-branch arm-stable`

`sudo pacman-mirrors --fasttrack 5 && sudo pacman -Syyu`

`pacman-mirrors` has got many options to configure the update process

https://wiki.manjaro.org/index.php?title=Switching_Branches

**Comment by bfra2373** [comment]
@mouffa Is that the same for Arch Linux?

**Comment by mouffa** [comment]
@bfra2373 It should work for any distribution that uses `pacman`, Manjaro Phosh is Arch Linux with the Phosh (Gnome) graphical environment.

**Comment by bfra2373** [comment]
oh my bad really! typo on my side *pacman-mirrors not pacman-mirror

**Comment by bfra2373** [comment]
@mouffa The Arch repo seem's is changed in the /etc/pacman.conf file as proposed by [ArchWiki](https://wiki.archlinux.org/title/Official_repositories) .
At the moment, the repo Danctnix stable repo call firefox 108.1... Manjaro probably hold some package a bit longer

**Comment by mouffa** [comment]
@bfra2373 I am using these images

https://github.com/manjaro-pinephone/phosh/releases

maybe you can remove the Danctnix repository from the mirror list `/etc/pacman.d/mirrorlist` and remove and reinstall Firefox, you may also now have mixed packages from Arch and Danctnix and this may cause problems

what image have you flashed ? 

I only have ever used the images from here

https://github.com/manjaro-pinephone/

**Comment by bfra2373** [comment]
@mouffa I use the this image [dreemurrs-embedded/Pine64-Arch](https://github.com/dreemurrs-embedded/Pine64-Arch) 

From my point of view, at the moment, it is still a bit faster then Manjaro's. 

I don't think it's a good idea to change to switch from the Arch repo to Manjaro's.. The Pinephone update have not been a stability success story on my side! Most of the time I had breakage and I had to flash the image over and over. But I do hope that it get better at some point.

**Comment by mouffa** [comment]
@bfra2373 The Manjaro Plasma sometimes can't start the GUI after the update and you have to connect the keybourd to continue updating from a terminal until all the necessary packages have been update. Manjaro Phosh has never caused me a problem. 

Since you use a different distribution search in their forum on how the system is updated, they may have the respective `stable`, `testing`, `unstable` branches and the maintainers are probably different ones than Manjaro's.

**Comment by mouffa** [comment]
@bfra2373 Manjaro Phosh updated Firefox to `108.0.1-1` and now it doesn't respond neither to any touch on the rendered page nor it can scroll the page except if you select the terminal keyboard and navigate with it, all the other buttons outside of the rendered page like back, reload, menu, new tab etc work normally.

**Comment by bfra2373** [comment]
firefox 108.0.2-1 seem's to work has expected

**Comment by mouffa** [comment]
@bfra2373 I opened an issue here,

https://github.com/manjaro-pinephone/phosh/issues/66

the problem has to do with the `mobile-config-firefox` package which contains Javascript files which are extracted in Firefox related folders and adapt it to the mobile screen
